return {
    COMMON_UNDEFINED = "Indefinido",
    COMMON_DATE_EMPTY = "-",
    COMMON_REQUIRED_PARAMS = "Parâmetros obrigatórios ausentes.",
    COMMON_NOT_PROVIDED = "Não fornecida",

    OCCURRENCE_STATUS_SERVED = "Pena cumprida",
    OCCURRENCE_STATUS_PENDING = "Pena a cumprir",
    OCCURRENCE_TITLE_PREFIX = "Ocorrência #%s",
    OCCURRENCE_SEARCH_NOT_FOUND = "Nenhum resultado encontrado para a busca realizada.",

    ERROR_REQUIRED_PARAMS = "Parâmetros obrigatórios ausentes.",
    ERROR_SUSPECT_DATA_INVALID = "Dados do suspeito inválidos ou ausentes.",
    ERROR_NO_CRIME_INFORMED = "Nenhum crime informado.",
    ERROR_OCCURRENCE_ID_NOT_INFORMED = "ID da ocorrência não informado.",
    ERROR_SUSPECT_ID_NOT_INFORMED = "ID do suspeito não informado.",
    ERROR_OCCURRENCE_CREATED_ID = "Erro ao recuperar o ID da ocorrência criada.",
    ERROR_OCCURRENCE_NOT_FOUND = "Ocorrência não encontrada.",
    ERROR_NO_CHANGES_DETECTED = "Nenhuma alteração detectada.",
    ERROR_OCCURRENCE_UPDATE_DB = "Erro ao atualizar a ocorrência no banco de dados.",

    PRISON_FINISH_SUCCESS = "Suspeito preso com sucesso.",
    PRISON_FINISH_SUCCESS_OFFLINE = "Suspeito preso com sucesso. O jogador receberá a pena ao entrar.",
    PRISON_PRISONED = "Você foi preso por %s meses.",
    PRISON_RELEASED = "Você foi solto.",
    PRISON_ESCAPE_ATTEMPT = "Você tentou fugir da prisão.",
    PRISON_DEATH = "Você morreu na prisão.",
    PRISON_TASK_DEFAULT_NAME = "Prisão",
    PRISON_TASK_DEFAULT_BLIP = "Tarefa da prisão",
    PRISON_TASK_START_FAILED = "Não foi possível iniciar a tarefa.",
    PRISON_TASK_STARTED = "Tarefa iniciada: %s",
    PRISON_TASK_REDUCE_FAILED = "Não foi possível reduzir sua pena agora.",
    PRISON_TASK_COMPLETED = "Tarefa concluída: %s. Pena reduzida em %s minutos.",
    PRISON_TASK_NOT_AVAILABLE = "Esta tarefa não está disponível agora.",
    PRISON_TASK_ALREADY_RUNNING = "Você já está em uma tarefa.",
    PRISON_TASK_COOLDOWN = "Aguarde antes de iniciar outra tarefa.",
    PRISON_TASK_NOT_NEAR = "Você precisa estar no local da tarefa.",
    PRISON_TASK_NOT_FINISHED = "A tarefa ainda não foi concluída.",
    PRISON_TASK_EXPIRED = "Tarefa expirada.",

    REPORT_DESCRIPTION_INVALID = "Descrição do chamado inválida.",
    REPORT_COORDS_INVALID = "Coordenadas do chamado inválidas.",
    REPORT_NOT_FOUND = "Chamado não encontrado.",
    REPORT_NOT_ANSWERED = "Chamado não atendido.",
    REPORT_ACCEPTED_BY_OTHER = "Este chamado já foi aceito por outro policial.",
    REPORT_HANDLED_BY_FORMAT = "#%s - %s",
    REPORT_ACCEPTED_NOTIFY = "Você aceitou o chamado #%s. Descrição: %s Criado por: %s. A localização do chamado foi marcada no seu GPS.",
    REPORT_LOCATION_BLIP = "Localização do chamado",

    OFFICER_RANK_UNDEFINED = "Patente indefinida",
    OFFICER_LOCATION_BLIP = "Localização do policial",
    OFFICER_TARGET_NOT_POLICE = "O jogador não é policial.",
    OFFICER_TARGET_OTHER_ORGANIZATION = "O policial pertence a outra organização.",
    OFFICER_TARGET_RANK_PROTECTED = "Você não pode gerenciar um policial de patente igual ou superior.",
    OFFICER_SELF_FIRE = "Você não pode se demitir.",
    OFFICER_SELF_PROMOTE = "Você não pode se promover.",
    OFFICER_SELF_DEMOTE = "Você não pode se rebaixar.",
    OFFICER_SELF_HIRE = "Você não pode se contratar.",
    OFFICER_NO_PERMISSION_FIRE = "Você não tem permissão para demitir este policial.",
    OFFICER_NO_PERMISSION_PROMOTE = "Você não tem permissão para promover este policial.",
    OFFICER_NO_PERMISSION_DEMOTE = "Você não tem permissão para rebaixar este policial.",
    OFFICER_NO_PERMISSION_HIRE = "Você não tem permissão para contratar este policial.",
    OFFICER_HIGHEST_RANK = "O policial já está na maior patente.",
    OFFICER_ALREADY_POLICE = "O jogador já é policial.",
    OFFICER_NOT_ONLINE = "O jogador não está online.",
    OFFICER_HIRE_REQUEST_TITLE = "Contratação policial",
    OFFICER_HIRE_REQUEST_DESCRIPTION = "Você foi convidado para ingressar na polícia.",
    OFFICER_HIRE_REQUEST_REJECTED = "O jogador recusou a solicitação de contratação.",

    REQUEST_ACCEPT_KEYMAPPING = "Aceitar solicitações.",
    REQUEST_REJECT_KEYMAPPING = "Rejeitar solicitações.",

    FINE_RECORD_CAN_NOT_CREATED_ID = "Erro ao criar registro de multa.",
    FINE_RECORD_INVALID_TYPE = "Tipo de registro de multa inválido.",
    FINE_RECORD_TARGET_REQUIRED = "Alvo do registro de multa não informado.",
    FINE_RECORD_FINE_ID_REQUIRED = "ID da multa não informado.",
    FINE_RECORD_NOT_FOUND = "Registro de multa não encontrado.",
    FINE_RECORD_STATUS_PENDING = "Pendente",

    ADAPTER_GLOBAL_VEHICLES_FUNCTION_NOT_FOUND = "Função de veículos globais não encontrada na base.",
}
